// Code generated by goctl. DO NOT EDIT.
package types

type DownloadRequest struct {
	File string `path:"file"`
}

type UploadResponse struct {
	Code int `json:"code"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type UserInfoResp struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avator    string `json:"avator"`
	Signature string `json:"signature"`
}

type DelReq struct {
	Id int64 `json:"id"`
}

type DelResp struct {
	Code int64 `json:"code"`
}

type ModifyAvatarReq struct {
	Username string `json:"username"`
}

type ModifyAvatarResp struct {
	Avator string `json:"avator"`
}

type CreateAttachmentReq struct {
	SummaryId string `json:"summaryId"`
	Url       string `json:"url"`
	Type      string `json:"type"`
}

type CreateAttachmentResp struct {
	Code string `json:"code"`
}

type CreateCommentReq struct {
	SummaryId string `json:"summaryId"`
	UserId    string `json:"userId"`
	Content   string `json:"content"`
}

type CreateCommentResp struct {
	Code int64 `json:"code"`
}

type RemoveCommentReq struct {
	SummaryId string `json:"summaryId"`
	UserId    string `json:"userId"`
}

type RemoveCommentResp struct {
	CreateCommentResp
}

type AddFollowReq struct {
	FollowerId string `json:"followerId"`
	FolloweeId string `json:"followeeId"`
}

type AddFollowResp struct {
	Code int64 `json:"code"`
}

type RemoveFollowReq struct {
	AddFollowReq
}

type RemoveFollowResp struct {
	AddFollowResp
}

type CreateImageReq struct {
	SummaryId string `json:"summaryId"`
	Url       string `json:"url"`
}

type CreateImageResp struct {
	Code int64 `json:"code"`
}

type AddLikeReq struct {
	SummaryId string `json:"summaryId"`
	UserId    string `json:"userId"`
}

type AddLikeResp struct {
	Code int64 `json:"code"`
}

type RemoveLikedReq struct {
	AddLikeReq
}

type RemoveLikedResp struct {
	AddLikeResp
}

type CreateSummaryReq struct {
	UserId   string `json:"username"`
	Title    string `json:"title"`
	Content  Array  `json:"content"`
	IsShared bool   `json:"isShared"`
}

type CreateSummaryResp struct {
	Code int64 `json:"code"`
}

type UpdateSummaryReq struct {
	CreateSummaryReq
}

type UpdateSummaryResp struct {
	CreateSummaryResp
}

type RemoveSummaryReq struct {
	Username string `json:"username"`
}

type RemoveSummaryResp struct {
	CreateSummaryResp
}

type Array struct {
	Array []string `form:"array"`
}
