// Code generated by goctl. DO NOT EDIT.
package types

type DownloadRequest struct {
	File string `path:"file"`
}

type UploadResponse struct {
	Code int `json:"code"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Mobile string `json:"mobile"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code         int64  `json:"code"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type UserInfoResp struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Collects  Array  `json:"collects"`
	Following Array  `json:"following"`
	Fan       int64  `json:"fan"`
}

type DelReq struct {
	Id int64 `json:"id"`
}

type DelResp struct {
	Code int64 `json:"code"`
}

type Array struct {
	Array []string `form:"array"`
}
