// Code generated by goctl. DO NOT EDIT.

package article

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articlesFieldNames          = builder.RawFieldNames(&Articles{})
	articlesRows                = strings.Join(articlesFieldNames, ",")
	articlesRowsExpectAutoSet   = strings.Join(stringx.Remove(articlesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articlesRowsWithPlaceHolder = strings.Join(stringx.Remove(articlesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheArticlesIdPrefix = "cache:articles:id:"
)

type (
	articlesModel interface {
		Insert(ctx context.Context, data *Articles) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Articles, error)
		Update(ctx context.Context, data *Articles) error
		Delete(ctx context.Context, id int64) error
	}

	defaultArticlesModel struct {
		sqlc.CachedConn
		table string
	}

	Articles struct {
		Id         int64          `db:"id"`
		Uid        int64          `db:"uid"` // 用户ID
		Cid        int64          `db:"cid"` // 类别ID
		CreateTime time.Time      `db:"create_time"`
		UpdateTime time.Time      `db:"update_time"`
		Title      string         `db:"title"`
		Content    string         `db:"content"`
		HeadImage  sql.NullString `db:"head_image"`
	}
)

func newArticlesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultArticlesModel {
	return &defaultArticlesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`articles`",
	}
}

func (m *defaultArticlesModel) Delete(ctx context.Context, id int64) error {
	articlesIdKey := fmt.Sprintf("%s%v", cacheArticlesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, articlesIdKey)
	return err
}

func (m *defaultArticlesModel) FindOne(ctx context.Context, id int64) (*Articles, error) {
	articlesIdKey := fmt.Sprintf("%s%v", cacheArticlesIdPrefix, id)
	var resp Articles
	err := m.QueryRowCtx(ctx, &resp, articlesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articlesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticlesModel) Insert(ctx context.Context, data *Articles) (sql.Result, error) {
	articlesIdKey := fmt.Sprintf("%s%v", cacheArticlesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, articlesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.Cid, data.Title, data.Content, data.HeadImage)
	}, articlesIdKey)
	return ret, err
}

func (m *defaultArticlesModel) Update(ctx context.Context, data *Articles) error {
	articlesIdKey := fmt.Sprintf("%s%v", cacheArticlesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articlesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Uid, data.Cid, data.Title, data.Content, data.HeadImage, data.Id)
	}, articlesIdKey)
	return err
}

func (m *defaultArticlesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheArticlesIdPrefix, primary)
}

func (m *defaultArticlesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articlesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultArticlesModel) tableName() string {
	return m.table
}
